version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ktf
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktf
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Named volume reference

volumes:
  postgres_data:
